version: '3'

services:
  webapp:
    image: ownhealthrecord
    ports:
      - 8989:80
    volumes:
      - ./src:/var/www/html:rw
  database:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - 3306:3306
    volumes:
      - ownhr_data:/var/lib/mysql

volumes:
  ownhr_data: